### PR TITLE
Field ID generation

### LINKED ISSUE #11: Crash on screen rotation with SelectionController.
The application crash on a screen rotation When a SelectionController is in the currently shown Form with an EditTextController or a SearchableSelectionController, with the Error:

    com.github.dkharrat.nexusdialog.sample E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.github.dkharrat.nexusdialog.sample, PID: 7355
        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.dkharrat.nexusdialog.sample/com.github.dkharrat.nexusdialog.sample.SimpleExample}: java.lang.ClassCastException: android.widget.TextView$SavedState cannot be cast to android.widget.Spinner$SavedState
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
            [...]
        Caused by: java.lang.ClassCastException: android.widget.TextView$SavedState cannot be cast to android.widget.Spinner$SavedState
            at android.widget.Spinner.onRestoreInstanceState(Spinner.java:762)
            [...]

The value of `SPINNER_ID` and `EDIT_TEXT_ID` seems to be mixed-up on the redraw (I don't really see why though), so changing the value of `SPINNER_ID` will solve the problem.

### PR DESCRIPTION
**Pull request by aveuiller**
The fix wasn't as easy as expected, but I have something. :)

I had to create every field View programmatically, because xml layouts will end with the same bug as #12, i.e. every field of the same type will share the same id, so Android will recognize them as the same and copy values between them on rotation.
So the Idea is that every field has a new ID when created. 

At this point, the rotation creates new fields (thus with different IDs), so their values weren't kept.
I had to make the `FormModel` Serializable in order to save it upon Activity destruction and re-set it on activity creation (which are called on a phone rotation without special treatment).

This will Close #11

### CODE REVIEW

**Comment by dkharrat** [comment]
Great! I appreciate the effort. I'll review the code soon and let you know of any feedback.

File: nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormModel.java [hunk 1]
```diff
@@ -2,12 +2,13 @@
...
 import java.beans.PropertyChangeListener;
 import java.beans.PropertyChangeSupport;
+import java.io.Serializable;
 
 /**
  * <code>FormModel</code> is an abstract class that represents the backing data for a form. It provides a mechanism
  * for form elements to retrieve their values to display to the user and persist changes to the model upon changes.
  */
-public abstract class FormModel {
+public abstract class FormModel implements Serializable {
```
Comment (dkharrat) [inline nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormModel.java]: I wonder if there's another way we can maintain the model instance on rotations besides implementing the `Serializable` interface. It's reasonable, but my main concern is that it might be a bit too restricting for users if they need to implement their own model. This essentially means their model and its class members must be `Serializable`.

It might be a reasonable restriction of there's no other way, but I'd like to make sure we explore other options too. Were there other ideas you considered?

**Comment by aveuiller** [comment]
I mainly looked at the [android documentation](http://developer.android.com/guide/topics/resources/runtime-changes.html), which provides two ways of doing it: 

1. Handle the configuration on the activity itself,
it prevents Android from recreating the view on rotation.
The main drawback being that it has to be declared on the manifest (so it is the user's responsability to declare it for each final activity).

2. Use a fragment and configure it to be retained between activity creations.
I originally tried to use this method on the FormController, which was clearly a bad idea, but looking back at the documentation made me realize It is possible to use this with the FormModel instead.

I tried the second option and it works well, making the `FormModel` a `Fragment` instead of `Serializable`, and using a `FragmentActivity` as a basis for the `FormActivity`.
Would that solution suits you better?

**Comment by dkharrat** [comment]
From those 2 options, I'd say approach 2 is definitely better.

Would you please squash your commits to 1 so I can merge it?

File: nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java [hunk 2]
```diff
@@ -11,7 +11,7 @@
  * {@link FormWithAppCompatActivity}
  */
 public abstract class FormActivity extends Activity {
-
+    private static final String MODEL_KW = "model";
```
Comment (dkharrat) [inline nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java]: Not sure what the `KW` part stands for. What do you think of `MODEL_BUNDLE_KEY` as the constant name? Also `MODEL_KEY` works.

Also, let's prefix the value with `nd_` (e.g. `nd_model`) to prevent collisions in case the the user also persists data in the Bundle.

File: nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java [hunk 3]
```diff
@@ -24,14 +24,24 @@ public void onCreate(Bundle savedInstanceState) {
         formController = new FormController(this);
         initForm();
 
+        if (savedInstanceState != null && savedInstanceState.containsKey(MODEL_KW)) {
+            FormModel savedModel = (FormModel) savedInstanceState.getSerializable(MODEL_KW);
+            formController.setModel(savedModel);
```
Comment (dkharrat) [inline nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java]: Do we also need to persist other state in `FormController`, like the error display validation method? What do you think is the best way to do that?

File: nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java (hunk 2 above)
Comment (aveuiller) [inline nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java]: KW stood for keyword, I will change it to MODEL_BUNDLE_KEY.

File: nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java (hunk 3 above)
Comment (aveuiller) [inline nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/FormActivity.java]: The validation of the form does not store data but only process every fields, the validation errors display only rely on an interface which is provided on the FormController creation.
The only drawback will be that any validation display on the form's fields will be reset until next validation. (if the validation display method uses the form at all)

So I don't really think the library has to handle this.

Having said that, if you really want to save the state of the validation display, I think the simplest way is to add errors  management methods to the `FormModel` (something like a `getError(String fieldName)` and `setError(String fieldName)`).
That way every persisted data will be stored in the FormData.

**Comment by dkharrat** [comment]
Merged the changes to master. Thanks for your contribution @aveuiller!
